#!/bin/sh

case "$1" in
    start)
        echo "Loading AESD Char Kernel Driver"
        /etc/aesdchar_load
        ;;
    stop)
        echo "Unloading AESD Char Kernel Driver"
        /etc/aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
